# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on: 
  push: 
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  api-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 6.0.x
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Install dependencies
      run: dotnet restore ./apps/webapi

    - name: Build
      run: dotnet build --configuration Release --no-restore ./apps/webapi

  ui-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x, 16.x] # Angular 12 no longer support Node.js version of < 15

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean Install
      working-directory: ./apps/choreui
      run: npm ci

    - name: Build
      working-directory: ./apps/choreui
      run: npm run build --if-present

    # - name: Test
    #   working-directory: ./apps/choreui
    #   run: npm test

  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: Compose Integration
      run: docker-compose -f docker-compose-full-integration.yml up -d
      
    - name: Integration Test
      run: newman run ./tests/Chores.postman_collection.json
