# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on: [push, pull_request]
  workflow_dispatch:

jobs:
  api-build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '5.0.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

  ui-build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean Install
      run: npm ci

    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm test

  integration-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: Compose Integration
      run: docker-compose -f docker-compose-full-integration.yml up -d
      
    - name: Integration Test
      run: newman run tests\Chores.postman_collection.json
